[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "qec_sim"
version = "0.1.0"
requires-python = ">=3.10"
description = "Quantum Error Correction Simulator with Correlated & Leakage Noise"
dependencies = [
    "numpy>=2.2.6",
    "torch>=2.9.0",
    "stim>=1.15.0",
    "pymatching>=2.3.1",
    "numba>=0.64.0",
    "tqdm>=4.67.1",
    "pyyaml>=6.0",
    "python-dotenv>=1.0",
    "quimb>=1.8",
    "beliefmatching>=0.2.0",
    "mlflow>=3.0",
]

[project.optional-dependencies]
analysis = [
    "jupyter>=1.1.1",
    "notebook>=7.5.3",
    "pandas>=2.3.3",
    "graphviz>=0.21",
    "torchviz>=0.0.3",
]

[tool.setuptools.packages.find]
where = ["."]

[dependency-groups]
dev = [
    "pytest>=9.0.3",
]
