# configs/experiment_mwpm.yaml
simulation:
  train_steps: 100000  # 온라인 학습이므로 epoch의 개념보다 step이나 가상 데이터셋 크기를 지정
  val_steps: 5000

code:
  distance: 5
  rounds: 5

noise:
  p_gate: [0.001, 0.005, 0.01]  # 3가지 확률에서 랜덤 샘플링
  p_meas: 0.005                 # 고정값
  p_corr: [0.001, 0.002]        # 2가지 확률에서 랜덤 샘플링
  p_leak: [0.01, 0.03, 0.05]    # 3가지 확률에서 랜덤 샘플링